"""Prompt construction with few-shot correction injection.

``PromptBuilder`` assembles the final prompt that is sent to the LLM.
It includes:
- All 5 anti-fabrication rules (Section 12 of the spec)
- Document-type context
- Raw vision-model output
- Few-shot corrections from ChromaDB (capped at ``MAX_FEW_SHOT_CORRECTIONS``)
- Token estimation to prevent prompt overflow
"""

from __future__ import annotations

import logging
import textwrap
from typing import Optional

from app.models.enums import DocumentType

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt configuration
# ---------------------------------------------------------------------------

MAX_FEW_SHOT_CORRECTIONS: int = 5
"""Maximum number of few-shot corrections to inject per prompt.
Hard limit to prevent context-window overflow (spec §12.8)."""

TOKENS_PER_WORD_ESTIMATE: float = 1 / 0.75  # ~1.33 tokens per word
"""Rough estimate: 1 token ≈ 0.75 words → words × 1.33 ≈ tokens."""

MAX_CONTEXT_TOKENS: int = 7000
"""Leave headroom below the 8192 context window for model output."""


class PromptBuilder:
    """Build deterministic extraction prompts with few-shot injection.

    The ``BASE_PROMPT`` template contains **all 5 anti-fabrication rules**
    from spec Section 12.  Every prompt generated by this class includes
    these rules unconditionally.
    """

    # ------------------------------------------------------------------
    # Base prompt template — ALL anti-fabrication rules are included here
    # ------------------------------------------------------------------
    BASE_PROMPT = textwrap.dedent(
        """\
        You are a deterministic document extraction engine for German bureaucratic forms.
        Your output MUST be deterministic (temperature = 0.0).

        === ANTI-FABRICATION RULES (mandatory — follow ALL of them) ===
        1. NO EXTRAPOLATION: If a field is empty (e.g. signature line), output null.
           Never infer, assume, or fabricate a value.
        2. NO AUTOCOMPLETE: If text is cut off (e.g. "Hauptstra..."), output EXACTLY
           what is visible. Do NOT complete the word. Flag with LOW_CONFIDENCE.
        3. DETERMINISTIC OUTPUT: Temperature is 0.0. Produce the exact same output
           every time for the same input. No creativity, no variation.
        4. UNRESOLVED FALLBACK: If a field is unclear, ambiguous, missing, or fails
           validation → set value to null and status to "UNRESOLVED".
        5. AUDIT TRAIL: Every extraction decision must be traceable. If you mark a
           field UNRESOLVED, do so explicitly — never silently omit it.
        === END RULES ===

        Document Type: {document_type}

        === FIELD GUIDE ===
        {field_guide}
        === END FIELD GUIDE ===

        === RAW VISION EXTRACTION ===
        {vision_output}
        === END VISION EXTRACTION ===

        {few_shot_section}

        Now extract structured data following the schema strictly.
        Output ONLY valid JSON matching the field guide exactly.
        Set unknown/missing/ambiguous fields to null with status "UNRESOLVED".
        """
    )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build(
        self,
        document_type: DocumentType,
        vision_output: str,
        corrections: list[dict],
        field_guide: Optional[str] = None,
    ) -> str:
        """Construct the final prompt for LLM extraction.

        Args:
            document_type: The detected document type (enum member).
            vision_output: Raw text output from the vision-model dual-pass.
            corrections: List of correction dicts with keys:
                ``original``, ``corrected``, ``reason``, ``field``.
            field_guide: Optional human-readable field listing. If not provided,
                a generic guide is generated from the document type name.

        Returns:
            The fully formatted prompt string.
        """
        few_shot_section = self.build_few_shot_section(corrections)

        if field_guide is None:
            field_guide = self._default_field_guide(document_type)

        prompt = self.BASE_PROMPT.format(
            document_type=document_type.value,
            field_guide=field_guide,
            vision_output=vision_output,
            few_shot_section=few_shot_section,
        )

        # Safety check: estimate token count and warn if we might overflow
        est_tokens = self.estimate_tokens(prompt)
        if est_tokens > MAX_CONTEXT_TOKENS:
            logger.warning(
                "Estimated prompt size (%.0f tokens) exceeds safe limit (%d). "
                "Consider truncating vision_output or reducing corrections.",
                est_tokens,
                MAX_CONTEXT_TOKENS,
            )

        logger.debug(
            "Built prompt: doc_type=%s, corrections=%d, est_tokens=%.0f",
            document_type.value,
            min(len(corrections), MAX_FEW_SHOT_CORRECTIONS),
            est_tokens,
        )

        return prompt

    def build_few_shot_section(self, corrections: list[dict]) -> str:
        """Format corrections for injection into the prompt.

        Corrections are capped at ``MAX_FEW_SHOT_CORRECTIONS`` (default 5).

        Args:
            corrections: List of correction dicts. Each dict should contain:
                - ``original``: the original (incorrect) extracted value
                - ``corrected``: the user-corrected value
                - ``reason``: explanation for the correction
                - ``field``: the field name this correction applies to

        Returns:
            Formatted few-shot section string, or empty string if no corrections.
        """
        if not corrections:
            return ""

        # Enforce hard limit
        capped = corrections[:MAX_FEW_SHOT_CORRECTIONS]
        if len(corrections) > MAX_FEW_SHOT_CORRECTIONS:
            logger.debug(
                "Truncated %d corrections to %d (MAX_FEW_SHOT_CORRECTIONS)",
                len(corrections),
                MAX_FEW_SHOT_CORRECTIONS,
            )

        lines = ["=== LEARNED CORRECTIONS (apply these patterns) ==="]
        for c in capped:
            lines.append(
                f"- Field '{c.get('field', 'unknown')}': "
                f"'{c.get('original', '')}' was corrected to '{c.get('corrected', '')}'. "
                f"Reason: {c.get('reason', 'N/A')}"
            )
        lines.append("=== END LEARNED CORRECTIONS ===")
        return "\n".join(lines)

    def build_correction_prompt(
        self,
        original_value: str,
        corrected_value: str,
        field_name: str,
    ) -> str:
        """Build a prompt for the learning-loop correction step.

        This is used when a user submits a correction so the LLM can
        generate an embedding-friendly description of what changed.

        Args:
            original_value: The originally extracted (incorrect) value.
            corrected_value: The user-provided correct value.
            field_name: The name of the field being corrected.

        Returns:
            A short prompt that can be fed back into the LLM for the
            correction learning loop.
        """
        return (
            f"Document field '{field_name}' was corrected:\n"
            f"  Original: '{original_value}'\n"
            f"  Corrected: '{corrected_value}'\n"
            "Explain briefly why this correction was needed. "
            "Keep your answer under 50 words."
        )

    @staticmethod
    def estimate_tokens(text: str) -> float:
        """Estimate the number of tokens for the given text.

        Uses the rough heuristic: ``token_count ≈ word_count / 0.75``
        (i.e. ~1.33 tokens per word).  This is a conservative upper bound
        for mixed text with the Llama BPE tokenizer.

        Args:
            text: The text to estimate.

        Returns:
            Estimated token count as a float.
        """
        word_count = len(text.split())
        return word_count * TOKENS_PER_WORD_ESTIMATE

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _default_field_guide(document_type: DocumentType) -> str:
        """Generate a minimal field guide when none is provided externally.

        Args:
            document_type: The document type enum member.

        Returns:
            A short field-listing string.
        """
        guides: dict[DocumentType, str] = {
            DocumentType.MELDEBESCHEINIGUNG: (
                "familienname, vorname, geburtsdatum (DD.MM.YYYY), geburtsort, "
                "staatsangehoerigkeit, strasse, hausnummer, postleitzahl (5 digits), "
                "wohnort, einzugsdatum (DD.MM.YYYY, optional), "
                "vorherige_anschrift (optional)"
            ),
            DocumentType.STEUERBESCHEID: (
                "steuer_id (11 digits), steuernummer, veranlagungsjahr, "
                "steuerart, zu_zahlen, erstattung, faellig_am (DD.MM.YYYY, optional), "
                "finanzamt"
            ),
            DocumentType.GEHALTSAUSWEIS: (
                "arbeitgeber, arbeitnehmer, abrechnungsmonat (MM.YYYY), "
                "brutto_lohn, netto_lohn, steuerklasse (I-VI), "
                "sozialversicherung, lohnsteuer, kirchensteuer (optional)"
            ),
            DocumentType.PERSONALAUSWEIS: (
                "familienname, vorname, geburtsdatum (DD.MM.YYYY), "
                "staatsangehoerigkeit, geburtsort, gueltig_bis (DD.MM.YYYY), "
                "ausweisnummer (9 characters)"
            ),
            DocumentType.UNBEKANNT: (
                "Unknown document type — extract any clearly legible fields. "
                "Mark all fields as UNRESOLVED if document type cannot be determined."
            ),
        }
        return guides.get(
            document_type,
            "Extract all visible fields. Mark unclear fields as UNRESOLVED.",
        )
